"use client";
import NavBar from "@/components/NavBar";
import "./globals.css";
import {Inter} from "next/font/google";
import {AppProgressBar as ProgressBar} from "next-nprogress-bar";
const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NavBar />
        <ProgressBar height='6px' color='#f97316' options={{showSpinner: false}} shallowRouting />
        {children}
      </body>
    </html>
  );
}
